### ISSUE TITLE
Clean incomplete sentences

### ISSUE THREAD

**Issue by Mte90** [common-voice/cv-sentence-extractor#143]
Some examples:
```
La società "Discordia Ltd.
Basta provare".
Fermi tutti!".
Maschinenfabrik" a Amburgo.
```

**Comment by MichaelKohler** [comment]
What exactly is the expectation here?

If those sentences need to be cleaned up from the existing sentences from CV, then you can create a PR against the wiki file in the CV repo. Sentences which have already been recorded won't be deleted though.

You might also want to look at `matching_symbols` for the Italian PR you are currently working on.

**Comment by Mte90** [comment]
I got those sentence with the WIP, the issue is that there is just one `"` so it is wrong as sentence.
