### ISSUE TITLE
Use best practice in English rules file

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/cv-sentence-extractor#156]
Over the past years there were quite a few changes to the possible rule configurations. The English rules file still uses some older rules that should now be replaced by better approaches, such as replacing `disallowed_symbols` with `allowed_symbols`.

As most new rule files get copied from EN, this would improve overall quality quite substantially.

**Comment by stefangrotz** [comment]
I would definitely add 

```
matching_symbols = [
  ["„", "“"],
  ["(", ")"]
]
```
and maybe also even_symbols

**Comment by MichaelKohler** [comment]
Nice, that's already done :)

**Comment by MichaelKohler** [comment]
Thanks, I've incorporated half of it.

> "^(Century|Other Example)"

.. is AFAICS not used in favor of 3rd etc. If you have others I'm happy to add those though.

> (^[A-Za-z]{1}\\s)

.. would discard all sentences starting with the article "a", such as "A brown fox jumps over the lazy dog", or any sentence starting with the personal pronon "I", such as "I went to school". Excluding A and I explicitely could make sense, but I'm really not sure if that's actually an issue in general.

> (\\s[A-Za-z]{1}[\\.|\\?|!]*$)

This would exclude sentences that end in "I",  but that IMHO isn't a problem.

**Comment by MichaelKohler** [comment]
Generally, do you think it would make sense to think about possible abbreviation replacements through `replacements`?

**Comment by stefangrotz** [comment]
I believe that this could be a good thing, since sometimes a word only exists in the form of abbreviations. People rarely write things like "Mister", so replacing "Mr." could improve the dataset.  I also believe that this could be extremely beneficial to small languages because replacing abbreviations could also increase the number of extracted sentences.
