### ISSUE TITLE
What is the limit for "replacements"?

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/cv-sentence-extractor#184]
So, we can pre-process Wiki sentences with replacements. One common usage is expanding abbreviations and acronyms. Of course, these are required for them to be useful in Common Voice.

In my own pre-processing scripts (for language models for example), I convert numbers to texts, run spellchecking and replace common misspellings etc. 

On the other hand, these replacements change the original text. Where should we stop - legally?

**Comment by MichaelKohler** [comment]
@jessicarose hi Jessica, is this something you could figure out with Legal?

**Comment by HarikalarKutusu** [comment]
This has been implemented as a rule with PR [#199](https://github.com/common-voice/cv-sentence-extractor/pull/199)
