### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/cv-sentence-extractor#82]
Currently the name of this repo suggests that only Wikipedia data can be scraped. While this is currently the case, the code base is ready to implement other sources as well. Therefore I'd suggest to rename the repo name (as well as the repo description at the top) to something that is more generic. I'd suggest "sentence-extractor", as Common Voice is kinda implied by the org already.

@Mte90 @nukeador any thoughts?

**Comment by Mte90** [comment]
what do you think of cv-extractor?

**Comment by MichaelKohler** [comment]
> what do you think of cv-extractor?

Would work for me.

**Comment by MichaelKohler** [comment]
@nukeador as I'm not an admin, can you rename the repo in the Settings to "cv-extractor" given that the org name already mentions "CommonVoice"?

**Comment by MichaelKohler** [comment]
(all old links will continue to work)

**Comment by nukeador** [comment]
Is "extractor" clear enough? Is this about extracting something on common voice or about getting sentences scrapped from different sources?

I would prefer something more like sentence-scrapper or sentence-extractor.

**Comment by MichaelKohler** [comment]
I could get behind sentence-extractor. Scraper is not really correct IMHO, as most of the scraping from a target source happens outside of this repo (such as manually downloading the dump from Wikipedia and preparing it to the right format).

**Comment by nukeador** [comment]
Renamed to cv-sentence-extractor

**Comment by MichaelKohler** [comment]
thanks!
